const ONE_SECOND = 1000;
const ONE_MINUTE = ONE_SECOND * 60;
const ONE_HOUR = ONE_MINUTE * 60;
const ONE_DAY = ONE_HOUR * 24;

export const TIME_IN_MS = {
	ONE_SECOND,
	ONE_MINUTE,
	ONE_HOUR,
	ONE_DAY,
};

export const TIME_IN_SECONDS = {
	ONE_SECOND: 1,
	ONE_MINUTE: 60,
	ONE_HOUR: 60 * 60,
	ONE_DAY: 24 * 60 * 60,
};
