version: '3'

services:
  postgres:
    image: postgres
    networks:
      - wetBatnetwork
    environment:
      POSTGRES_USER: "${TYPEORM_USERNAME}"
      POSTGRES_PASSWORD: "${TYPEORM_PASSWORD}"
      POSTGRES_DB: "${TYPEORM_DATABASE}"
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres:/var/wetBat/postgres/data
  redis:
    image: redis
    networks:
      - wetBatnetwork
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/var/wetBat/redis/data
  mongo:
      image: mongo
      networks:
        - wetBatnetwork
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      ports:
        - "${MONGODB_PORT}:${MONGODB_PORT}"
      volumes:
        - mongo:/var/wetBat/mongo/data
      command: mongod
  mail:
    image: mailhog/mailhog
    networks:
      - wetBatnetwork
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  wetBatnetwork:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
  mongo:
  mail:
